services:
  workspace:
    build: .
    command: sleep infinity
    volumes:
      - ./:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - pgadmin

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: devtedsuser
      POSTGRES_PASSWORD: devtedspass
      POSTGRES_DB: demodb
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devtedsuser -d demodb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@interview.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgadmin-data:
  pg-data:
